spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 66921987265-jjcf6teo4h8o2rc3v1sqgfp5va2phhfd.apps.googleusercontent.com
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope: ${OAUTH_GOOGLE_SCOPE}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            required: true
            enable: ${MAIL_SMTP_STARTTLS}
  application:
    name: oneblog
security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
