spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    contexts: dev
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        web:
          DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

