spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: yakup_jr
    password: 13579
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        web:
          DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE



message-from-application-properties: Hello from application-dev.properties
