spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://ep-mute-voice-a29cocai.eu-central-1.aws.neon.tech/oneblog
    username: oneblog_owner
    password: hBAgwKiMOu62
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        web:
          DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE



message-from-application-properties: Hello from application-dev.properties
