[versions]
springBoot = "3.3.1"
springDependencyManagement = "1.1.5"
jjwt = "0.13.0"
mapstruct = "1.6.3"
liquibase = "4.33.0"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter"}
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-boot-testcontainers = {module = "org.springframework.boot:spring-boot-testcontainers"}

spring-hateoas = { module = "org.springframework.hateoas:spring-hateoas" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

lombok = { module = "org.projectlombok:lombok" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

postgresql = { module = "org.postgresql:postgresql" }
hikari = { module = "com.zaxxer:HikariCP" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }

jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

spring-security-test = { module = "org.springframework.security:spring-security-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-postgresql = {module = "org.testcontainers:postgresql"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }