spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${DATASOURCE_URL}
    username: ${file(/run/secrets/db_username)}
    password: ${file(/run/secrets/db_password)}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${file(/run/secrets/oauth_google_client_id)}
            client-secret: ${file(/run/secrets/oauth_google_client_secret)}
            scope: email,profile
  liquibase:
    contexts: prod
    change-log: db/changelog/db.changelog-master-prod.yml
  mail:
    host: smtp.resend.com
    port: 587
    username: ${file(/run/secrets/mail_username)}
    password: ${file(/run/secrets/mail_password)}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
  application:
    name: oneblog
security:
  jwt:
    secret_key: ${file(/run/secrets/jwt_secret_key)}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
