name: CI/CD Pipeline

on: push

env:
  DOCKER_IMAGE: 'docker:stable'
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_BUILD: whtoy/oneblog

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "gradle:8.13.0-jdk21"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gradle assemble
        run: gradle assemble

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      DOCKER_HOST: "tcp://docker:2375"
      TESTCONTAINERS_RYUK_DISABLED: "true"
      TC_REUSE_CONTAINER: "true"
      TESTCONTAINERS_REUSE_ENABLE: "true"
      DOCKER_API_VERSION: "1.41"
      TESTCONTAINERS_CHECKS_DISABLE: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Gradle check
        run: gradle check

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: build/test-results/test/TEST-*.xml

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build JAR
        run: gradle clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_BUILD }}:dev-latest
            ${{ env.DOCKER_IMAGE_BUILD }}:dev-1.0.${{ github.run_number }}

  deploy-main:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Build and push main image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_BUILD }}:latest
            ${{ env.DOCKER_IMAGE_BUILD }}:1.0.${{ github.run_number }}